# Generated by Django 5.2.11 on 2026-03-16 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_leaserequest_requested_area'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowaccount',
            name='amount_received',
            field=models.BooleanField(default=False, help_text='True when lessee has completed M-Pesa payment'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='amount_received_at',
            field=models.DateTimeField(blank=True, help_text='When payment was received in escrow', null=True),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='lessee_agreed',
            field=models.BooleanField(default=False, help_text='Lessee has agreed (signed agreement)'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='lessee_signed_at',
            field=models.DateTimeField(blank=True, help_text='When lessee signed agreement', null=True),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='owner_approved_release',
            field=models.BooleanField(default=False, help_text='Owner has approved escrow release'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='owner_signed',
            field=models.BooleanField(default=False, help_text='Owner has signed agreement'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='owner_signed_at',
            field=models.DateTimeField(blank=True, help_text='When owner signed agreement', null=True),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount refunded to lessee', max_digits=12),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When escrow was refunded to lessee', null=True),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When escrow was released to owner', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, help_text='M-Pesa CheckoutRequestID from STK Push', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_result_code',
            field=models.CharField(blank=True, help_text='Result code from M-Pesa callback (0 = success)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_result_desc',
            field=models.TextField(blank=True, help_text='Result description from M-Pesa', null=True),
        ),
        migrations.AlterField(
            model_name='escrowaccount',
            name='released_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount released to owner', max_digits=12),
        ),
        migrations.AlterField(
            model_name='escrowaccount',
            name='status',
            field=models.CharField(choices=[('awaiting_signature', 'Awaiting Both Signatures'), ('both_signed', 'Both Signed - Ready to Release'), ('released', 'Released to Owner'), ('refunded', 'Refunded to Lessee'), ('disputed', 'Disputed')], default='awaiting_signature', help_text='Escrow release is tied to lease agreement signing', max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='mpesa_receipt',
            field=models.CharField(blank=True, help_text='M-Pesa receipt number for successful payment', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mpesa', 'M-Pesa'), ('escrow', 'Escrow'), ('bank_transfer', 'Bank Transfer')], default='mpesa', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('stk_initiated', 'STK Push Initiated'), ('user_cancelled', 'User Cancelled'), ('completed', 'Completed'), ('failed', 'Failed'), ('in_escrow', 'In Escrow')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('rent_payment', 'Rent Payment'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('withdrawal', 'Withdrawal'), ('deposit', 'Deposit')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['checkout_request_id'], name='payments_tr_checkou_34e8a5_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_id'], name='payments_tr_transac_e96a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'status'], name='payments_tr_user_id_b99a80_idx'),
        ),
    ]
