# Generated by Django 5.2.11 on 2026-02-27 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('landmanagement', '0002_alter_landlisting_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_start_date', models.DateField()),
                ('proposed_end_date', models.DateField()),
                ('proposed_rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_requests', to='landmanagement.landlisting')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('land', 'lessee', 'status')},
            },
        ),
        migrations.CreateModel(
            name='LeaseAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending_signature', 'Pending Signature'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending_signature', max_length=20)),
                ('owner_signed', models.BooleanField(default=False)),
                ('lessee_signed', models.BooleanField(default=False)),
                ('owner_signed_at', models.DateTimeField(blank=True, null=True)),
                ('lessee_signed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='landmanagement.landlisting')),
                ('lessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessee_agreements', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_agreements', to=settings.AUTH_USER_MODEL)),
                ('lease_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='contracts.leaserequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
