# Generated by Django 5.2.11 on 2026-03-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaseagreement',
            name='intended_use',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lessee_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lessee_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='lessee_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='owner_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='special_conditions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='witness_id_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='witness_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='witness_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='witness_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaseagreement',
            name='witness_signed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
