# Generated by Django 5.2.11 on 2026-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_leaseagreement_intended_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaserequest',
            name='requested_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Acres requested (for partial lease from a larger plot)', max_digits=10, null=True),
        ),
    ]
