# Generated by Django 5.2.11 on 2026-02-20 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_month', models.DecimalField(decimal_places=2, max_digits=12)),
                ('preferred_duration', models.CharField(max_length=50)),
                ('has_irrigation', models.BooleanField(default=False)),
                ('has_electricity', models.BooleanField(default=False)),
                ('has_road_access', models.BooleanField(default=False)),
                ('has_fencing', models.BooleanField(default=False)),
                ('location_name', models.CharField(default='Unknown Location', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title_deed_number', models.CharField(help_text='The official registration number from the Ministry of Lands', max_length=255, unique=True)),
                ('status', models.CharField(choices=[('Vacant', 'Vacant'), ('Pending_Payment', 'Pending Payment'), ('Leased', 'Leased'), ('Under_Review', 'Under Review')], default='Vacant', max_length=20)),
                ('current_lessee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_lands', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='land_photos/')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='landmanagement.landlisting')),
            ],
        ),
        migrations.CreateModel(
            name='SoilClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph_level', models.FloatField()),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('moisture', models.FloatField()),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('land', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soil_data', to='landmanagement.landlisting')),
            ],
        ),
    ]
