# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlisting',
            name='title_deed_number',
            field=models.CharField(
                blank=True,
                help_text='For admin verification only',
                max_length=100,
                null=True
            ),
        ),
    ]
