# Generated by Django 5.2.11 on 2026-02-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlisting',
            name='status',
            field=models.CharField(choices=[('Vacant', 'Vacant'), ('Pending_Payment', 'Pending Payment'), ('Leased', 'Leased'), ('Under_Review', 'Under Review')], default='Under_Review', max_length=20),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='title_deed_number',
            field=models.CharField(help_text='For admin verification only — compulsory', max_length=100),
        ),
    ]
