# Generated by Django on 2026-03-09
# Manual migration to add missing fields

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('landmanagement', '0002_alter_landlisting_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlisting',
            name='location_name',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='current_lessee',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='rented_lands',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
