# Generated by Django 5.2.11 on 2026-02-20 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0002_landlisting_title_deed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlisting',
            name='verification_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='soilclimatedata',
            name='soil_type',
            field=models.CharField(blank=True, help_text='e.g., Clay, Loam, Sandy, Silt', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='title_deed_number',
            field=models.CharField(default='PENDING', help_text='For admin verification only - REQUIRED', max_length=100),
        ),
        migrations.AlterField(
            model_name='soilclimatedata',
            name='moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilclimatedata',
            name='nitrogen',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilclimatedata',
            name='ph_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilclimatedata',
            name='phosphorus',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilclimatedata',
            name='potassium',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilclimatedata',
            name='rainfall',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='soilclimatedata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('title_deed', 'Title Deed Verification'), ('land_approval', 'Land Listing Approval'), ('dispute', 'Dispute Resolution'), ('payment', 'Payment Issue')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('land', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='landmanagement.landlisting')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
