# Generated by Django 5.2.11 on 2026-03-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0002_alter_landlisting_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landlisting',
            name='preferred_duration',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
