# Generated by Django 5.2.11 on 2026-02-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0003_landlisting_verification_pending_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landlisting',
            name='verification_pending',
        ),
        migrations.AddField(
            model_name='landlisting',
            name='flag_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landlisting',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soilclimatedata',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='soilclimatedata',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='landlisting',
            name='title_deed_number',
            field=models.CharField(help_text='For admin verification only — compulsory', max_length=100),
        ),
        migrations.AlterField(
            model_name='soilclimatedata',
            name='soil_type',
            field=models.CharField(blank=True, choices=[('Sandy', 'Sandy'), ('Clay', 'Clay'), ('Loamy', 'Loamy'), ('Silt', 'Silt'), ('Peat', 'Peat'), ('Chalk', 'Chalk'), ('Sandy Loam', 'Sandy Loam'), ('Clay Loam', 'Clay Loam'), ('Other', 'Other')], help_text='General soil classification', max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='AdminNotification',
        ),
    ]
