# Generated by Django 5.2.11 on 2026-03-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0003_alter_landlisting_preferred_duration'),
        ('landmanagement', '0003_landlisting_location_name_landlisting_current_lessee'),
    ]

    operations = [
    ]
