# Generated by Django 5.2.11 on 2026-03-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0004_merge_20260311_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlisting',
            name='leased_area',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Acres currently under active lease (supports partial leases)', max_digits=10, null=True),
        ),
    ]
