# Generated by Django 5.2.11 on 2026-03-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0004_merge_20260311_1033'),
        ('landmanagement', '0005_landlisting_leased_area'),
    ]

    operations = [
    ]
