# Generated by Django 5.2.11 on 2026-03-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landmanagement', '0006_merge_20260313_1456'),
        ('landmanagement', '0007_add_missing_soilclimate_fields'),
    ]

    operations = [
    ]
